---
version: "3.8"
name: post-guac-flared

services:
  postguac:
    restart: unless-stopped
    container_name: postguac
    hostname: postguac
    image: rapidfort/postgresql:latest
    volumes:
      - postgres-db:/bitnami/postgresql
    environment:
      - POSTGRES_DATABASE=
      - POSTGRES_USER=
      - POSTGRESQL_PASSWORD=
    networks:
      - avocado-farm

  guacozy:
    restart: unless-stopped
    container_name: guacozy
    hostname: guacozy
    image: guacozy/guacozy-server:latest
    environment:
      DJANGO_SECRET_KEY:
      FIELD_ENCRYPTION_KEY:
      DJANGO_DB_URL: postgres://user:password@host:port/db-name
      DJANGO_ALLOWED_HOSTS: "*"
      SUPERUSER_NAME:
      SUPERUSER_EMAIL:
      SUPERUSER_PASSWORD:
    expose:
      - 10080:80
      - 10443:443
    configs:
      - source: guac_conf
        target: /etc/guacamole/guacamole.properties
        mode: 662
      - source: guac_logback_config
        target: /etc/guacamole/logback.xml
        mode: 662
    networks:
      - farm-break
      - avocado-farm
    depends_on:
      - postguac

  guac-d:
    restart: unless-stopped
    container_name: guac-d
    hostname: guac-d
    image: guacamole/guacd:latest
    privileged: true
    environment:
      - GUACD_LOG_LEVEL=info
      - GUACD_HOST=guac-d
      - GUACD_PORT=4822
    networks:
      - avocado-farm

    #  - GUACDD_SERVER_CERTIFICATE=
    #  - GUACD_SERVER_KEY=
    #configs:
    #  - source: guac_d_conf
    #    target: /etc/guacamole/guacd.conf
    #    mode: 772
    #    uid: "1000"
    #    gid: "1000"

  guac-flared:
    restart: unless-stopped
    container_name: guac-flared
    hostname: guac-flared
    image: cloudflare/cloudflared:latest
    privileged: true
    command: "tunnel run $$TUNNEL_UUID"
    entrypoint: "cloudflared"
    user: root
    environment:
      TUNNEL_UUID: ""
      TUNNEL_TOKEN: ""
      TUNNEL_RETRIES: 5
      TUNNEL_TRANSPORT_PROTOCOL: auto
      TUNNEL_METRICS: localhost:12345
      TUNNEL_LOGLEVEL: info
      TUNNEL_LOGFILE: /var/log/cloudflared.log
      TUNNEL_ORIGIN_CERT: /etc/cloudflared/cert.pem
      NO_AUTOUPDATE: false
    networks:
      - farm-break
      - avocado-farm
    secrets:
      - source: cloudflared-origin-cert
        target: /etc/cloudflared/cert.pem

networks:
  farm-break:
    external: true
    name: farm-break
  avocado-farm:
    external: true
    name: avocado-farm

volumes:
  postgres-db:
    name: postguacflared-vol
    external: true

secrets:
  cloudflared-origin-cert:
    name: cloudflared-origin-cert
    file: ./cert.pem

configs:
  guac_logback_config:
    name: guac_logback_config
    content: |
      <configuration>
          <!-- Appender for debugging -->
          <appender name="GUAC-DEBUG" class="ch.qos.logback.core.ConsoleAppender">
              <encoder>
                  <pattern>"%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"</pattern>
              </encoder>
          </appender>
          <!-- Log at DEBUG level -->
          <root level="info">
              <appender-ref ref="GUAC-DEBUG"/>
          </root>
      </configuration>

  guac_conf:
    name: guac_conf
    content: |
      api-session-timeout: 60
      available-languages: "en, de, es"
      enable-environment-properties: true
      guacd-hostname: guac-d
      guacd-port: 4822
      guacd-ssl: false
